### PR TITLE
Add an example configuration for scheduling.

### PR DESCRIPTION
**Pull request by mjethanandani**
Address issue #116.

I do not know if this example makes sense, so I am hoping a critical input on how we can demonstrate an example configuration for scheduling.

### CODE REVIEW

**Review by aseemavi — COMMENTED** [review]
No, better we should put scheduler policy + queueing Policy + inline policy example. I had been workin on one but I am getting a peculiar problem.. Let me upload and see if you can help there..

**Comment by mjethanandani** [comment]
> No, better we should put scheduler policy + queueing Policy + inline policy example. I had been workin on one but I am getting a peculiar problem.. Let me upload and see if you can help there..

Perfect!

BTW, I also thought of having scheduling and queuing, but decided to do one first, get it to work, then add the second (and in your case the third). Might help zero in on the error.

**Comment by aseemavi** [comment]
> > No, better we should put scheduler policy + queueing Policy + inline policy example. I had been workin on one but I am getting a peculiar problem.. Let me upload and see if you can help there..
> 
> Perfect!
> 
> BTW, I also thought of having scheduling and queuing, but decided to do one first, get it to work, then add the second (and in your case the third). Might help zero in on the error.

check this: https://github.com/mjethanandani/qos-yang/pull/123/files .. there is issue with xml-ns: xmlns="urn:ietf:params:xml:ns:yang:ietf-queue-policy" and xmlns="urn:ietf:params:xml:ns:yang:ietf-scheduler-policy"

**Comment by aseemavi** [comment]
closing it and replace with #128

**Pull request closed without merging**
